# Part 1. Python Basics

In [1]:
myList = ["Cat", "Dog", "Pigeon"]
print(myList[0])
print(myList[1])
print(myList[-1])

Cat
Dog
Pigeon


In [2]:
myList.append("Horse")
print(myList)

myList.insert(2, "Fish")
print(myList)

newList = ["Math", "English", "History"]
myList.extend(newList)
print(myList)

['Cat', 'Dog', 'Pigeon', 'Horse']
['Cat', 'Dog', 'Fish', 'Pigeon', 'Horse']
['Cat', 'Dog', 'Fish', 'Pigeon', 'Horse', 'Math', 'English', 'History']


In [3]:
myList.remove("Horse")

print(myList)
for x in myList:
    print(x)

['Cat', 'Dog', 'Fish', 'Pigeon', 'Math', 'English', 'History']
Cat
Dog
Fish
Pigeon
Math
English
History


In [4]:
myTuple = ("Time", "is", "Essential", "!")
print(myTuple)

('Time', 'is', 'Essential', '!')


In [8]:
print(myTuple[0])
print(myTuple[-1])
print(myTuple[1:4])

(happy, sad, bored, interested) = myTuple
print(happy)
print(interested)

Time
!
('is', 'Essential', '!')
Time
!


In [9]:
for i in range(len(myTuple)):
    print(myTuple[i])

Time
is
Essential
!


In [12]:
myDict = {
    "Flavor" : "Strawberry",
    "Format" : "Cone",
    "# of scoops" : 3
    }
print(myDict)
print(myDict["Flavor"])

{'Flavor': 'Strawberry', 'Format': 'Cone', '# of scoops': 3}
Strawberry


In [13]:
x = myDict.keys()
print(x)
y = myDict.values()
print(y)
z = myDict.items()
print(z)

dict_keys(['Flavor', 'Format', '# of scoops'])
dict_values(['Strawberry', 'Cone', 3])
dict_items([('Flavor', 'Strawberry'), ('Format', 'Cone'), ('# of scoops', 3)])


In [14]:
myDict["color"] = "pink"
print(myDict)

{'Flavor': 'Strawberry', 'Format': 'Cone', '# of scoops': 3, 'color': 'pink'}


In [15]:
myDict.update({"Format" : "cup"})
print(myDict)

myDict.update({"price": 5})
print(myDict)

{'Flavor': 'Strawberry', 'Format': 'cup', '# of scoops': 3, 'color': 'pink'}
{'Flavor': 'Strawberry', 'Format': 'cup', '# of scoops': 3, 'color': 'pink', 'price': 5}


In [16]:
myDict.pop("color")
print(myDict)

{'Flavor': 'Strawberry', 'Format': 'cup', '# of scoops': 3, 'price': 5}


In [18]:
print("====items====")
for x, y in myDict.items():
    print(x,":", y)

====items====
Flavor : Strawberry
Format : cup
# of scoops : 3
price : 5


# Part 2. Vector and Matrix

In [5]:
import pandas as pd

matrix = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9],
    'D': [10, 11, 12]
})

x1 = matrix.iloc[:, 0]
x2 = matrix.iloc[:, -2]

print(x1)
print(x2)

0    1
1    2
2    3
Name: A, dtype: int64
0    7
1    8
2    9
Name: C, dtype: int64


In [11]:
# 1. addition and subtraction
add = x1 + x2
print(add)
sub = x2 - x1
print(sub)

# 2. element-wise multiplication
mult = x1 * x2
print(mult)

# 3. inner product
import numpy as np
inPro = np.dot(x1, x2)
print(inPro)

# 4. three norms
norm1 = np.linalg.norm(x1 - x2, ord=1)

norm2 = np.linalg.norm(x1 - x2, ord=2)

inf_norm = np.linalg.norm(x1 - x2, ord=np.inf)

print(norm1)
print(norm2)
print(inf_norm)

# 5. compute the distance between these two vectors
distance = np.linalg.norm(x1 - x2)
print("Distance = {distance}")

0     8
1    10
2    12
dtype: int64
0    6
1    6
2    6
dtype: int64
0     7
1    16
2    27
dtype: int64
50
18.0
10.392304845413264
6.0
Distance = {distance}


In [14]:
df = pd.read_csv('cars.csv')
X = df.values[:, 1:-1]
matrix1 = X[:3, :3]
matrix2 = X[-3:, -3:]
print(matrix1)
print(matrix2)

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]]
[[2295 11.6 82]
 [2625 18.6 82]
 [2720 19.4 82]]


In [25]:
# 1. addition and subtraction 
matrix = matrix1 + matrix2
print(matrix)

# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
transpose = np.transpose(matrix2)
print(transpose)
print(transpose.shape)  

# 3. compute the product between A and C, and print the result and its shape
mult = np.dot(matrix1, matrix)
print(mult)
print(mult.shape)

# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
transpose2 = np.transpose(matrix1)
print(transpose2)
print(transpose2.shape)

# 5. compute the product between D and B, and print the result and its shape
mult2 = np.dot(matrix2, transpose2)
print(mult2)
print(mult2.shape)

[[2313.0 19.6 389.0]
 [2640.0 26.6 432.0]
 [2738.0 27.4 400.0]]
[[2295 2625 2720]
 [11.6 18.6 19.4]
 [82 82 82]]
(3, 3)
[[903320.0 8977.4 133258.0]
 [1014115.0 10096.8 149291.0]
 [933438.0 9278.8 137658.0]]
(3, 3)
[[18.0 15.0 18.0]
 [8 8 8]
 [307.0 350.0 318.0]]
(3, 3)
[[66576.8 63217.8 67478.8]
 [72572.8 68223.8 73474.8]
 [74289.2 69655.2 75191.2]]
(3, 3)
